In [6]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine

In [8]:
wine = load_wine()
wine.data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [18]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [20]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [24]:
df=pd.DataFrame(wine.data,columns=wine.feature_names)
df['wine_type']=wine.target
df.sample(10)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
53     13.77        1.90  2.68               17.1      115.0           3.00   
153    13.23        3.30  2.28               18.5       98.0           1.80   
141    13.36        2.56  2.35               20.0       89.0           1.40   
152    13.11        1.90  2.75               25.5      116.0           2.20   
91     12.00        1.51  2.42               22.0       86.0           1.45   
64     12.17        1.45  2.53               19.0      104.0           1.89   
61     12.64        1.36  2.02               16.8      100.0           2.02   
24     13.50        1.81  2.61               20.0       96.0           2.53   
149    13.08        3.90  2.36               21.5      113.0           1.41   
40     13.56        1.71  2.31               16.2      117.0           3.15   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
53         2.79                  0.39             1.68             6.30  1.13   
153        0.83                  0.61             1.87            10.52  0.56   
141        0.50                  0.37             0.64             5.60  0.70   
152        1.28                  0.26             1.56             7.10  0.61   
91         1.25                  0.50             1.63             3.60  1.05   
64         1.75                  0.45             1.03             2.95  1.45   
61         1.41                  0.53             0.62             5.75  0.98   
24         2.61                  0.28             1.66             3.52  1.12   
149        1.39                  0.34             1.14             9.40  0.57   
40         3.29                  0.34             2.34             6.13  0.95   

     od280/od315_of_diluted_wines  proline  wine_type  
53                           2.93   1375.0          0  
153                          1.51    675.0          2  
141                          2.47    780.0          2  
152                          1.33    425.0          2  
91                           2.65    450.0          1  
64                           2.23    355.0          1  
61                           1.59    450.0          1  
24                           3.82    845.0          0  
149                          1.33    550.0          2  
40                           3.38    795.0          0

In [34]:
#Features demonstarted by capitalized letter as such so it dictates it's a multi dimensional array
X=wine.data
X[:2]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03]])

In [36]:
#Label
y=wine.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [40]:
from sklearn.model_selection import train_test_split

In [44]:
# dividing data into training and testing set (0.2 -> 20% data on training set)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [56]:
from sklearn.preprocessing import StandardScaler

In [58]:
scaler=StandardScaler()

In [64]:
X_train=scaler.fit_transform(X_train)

In [66]:
X_test=scaler.transform(X_test)

In [68]:
from sklearn.neighbors import KNeighborsClassifier

In [72]:
knn = KNeighborsClassifier(n_neighbors=5)  #here k = 5

In [74]:
knn.fit(X_train,y_train)

KNeighborsClassifier()

In [78]:
y_pred=knn.predict(X_test)

In [84]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [86]:
accuracy_score(y_test,y_pred)

0.9444444444444444

In [88]:
confusion_matrix(y_test,y_pred)

array([[14,  0,  0],
       [ 1, 12,  1],
       [ 0,  0,  8]], dtype=int64)

In [92]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       1.00      0.86      0.92        14
           2       0.89      1.00      0.94         8

    accuracy                           0.94        36
   macro avg       0.94      0.95      0.94        36
weighted avg       0.95      0.94      0.94        36

